/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CodePlatform: typeof import('./src/components/CodePlatform/index.vue')['default']
    Dropdown: typeof import('./src/components/Tiptap/components/Table/dropdown.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElInput: typeof import('./src/components/Tiptap/components/ElInput/ElInput.vue')['default']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Index2: typeof import('./src/components/RequestAnimate/index2.vue')['default']
    Message: typeof import('./src/components/Message/index.vue')['default']
    RequestAnimate: typeof import('./src/components/RequestAnimate/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScalePicture: typeof import('./src/components/ScalePicture/index.vue')['default']
    Table: typeof import('./src/components/Tiptap/components/Table/index.vue')['default']
    Tiptap: typeof import('./src/components/Tiptap/index.vue')['default']
  }
}
